// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLhMoCHTtuRw_7hAjcKej6MOn8yZ0N6nI',
    appId: '1:87349799268:web:66dec023934d3905d3f271',
    messagingSenderId: '87349799268',
    projectId: 'virtual-nature-tour-b9a82',
    authDomain: 'virtual-nature-tour-b9a82.firebaseapp.com',
    storageBucket: 'virtual-nature-tour-b9a82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhgSSZG05A7UCSQ1n1Twl-b1bpY9Ufl2k',
    appId: '1:87349799268:android:4ff94eca25f78a97d3f271',
    messagingSenderId: '87349799268',
    projectId: 'virtual-nature-tour-b9a82',
    storageBucket: 'virtual-nature-tour-b9a82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyn5PPZDAB-Dn_KR-WwerglG5K6zLLr3A',
    appId: '1:87349799268:ios:60634942cc2327bad3f271',
    messagingSenderId: '87349799268',
    projectId: 'virtual-nature-tour-b9a82',
    storageBucket: 'virtual-nature-tour-b9a82.appspot.com',
    iosClientId: '87349799268-oba0pht9sqce4eus8ur0ksn9gnoia6pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualNatureAppTour',
  );
}
